{"tests": [{"data": {"status": "failure", "tool_id": "4c_addfragments", "time_seconds": 24.86878204345703, "inputs": {"input1": {"src": "hda", "id": "2891970512fa2d5a"}}, "tool_version": "1.0.0", "output_problems": ["Job in error state.", "Job in error state."], "job": {"inputs": {"input1": {"src": "hda", "id": "2891970512fa2d5a", "uuid": "b03f9cf4-cc08-4607-bfb8-b72279795dad"}}, "update_time": "2019-01-23T12:43:01.299292", "tool_id": "4c_addfragments", "outputs": {"output1": {"src": "hda", "id": "5729865256bc2525", "uuid": "66aa0fba-10df-4f60-a528-1a45514de8d4"}}, "stdout": "Failed to activate conda environment! Error was:\n/home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n", "command_line": "Rscript '/tmp/tmpWZS6PQ/job_working_directory/000/2/tmps5FlOT'", "exit_code": 1, "state": "error", "create_time": "2019-01-23T12:42:37.990070", "params": {"chromInfo": "\"/tmp/tmpWZS6PQ/galaxy-dev/tool-data/shared/ucsc/chrom/?.len\"", "dbkey": "\"?\""}, "stderr": "Fatal error: Exit code 1 ()\n", "job_metrics": [], "model_class": "Job", "external_id": "29803", "id": "5729865256bc2525", "user_email": "test@bx.psu.edu"}, "problem_log": "  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/test/functional/test_toolbox.py\", line 99, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/test/functional/test_toolbox.py\", line 36, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/lib/galaxy/tools/verify/interactor.py\", line 702, in verify_tool\n    raise e\nJob in error state.\nJob in error state.\n-------------------- >> begin captured stdout << ---------------------\nProblem in history with id 2891970512fa2d5a - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - fcdata.rdata (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  165.8 KB\n| Dataset Info:\n|  uploaded rdata file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>binary data</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - addFragments (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n|  Fatal error: Exit code 1 ()\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|\n--------------------------------------\n| Job 5729865256bc2525\n| State: \n|  error\n| Update Time:\n|  2019-01-23T12:43:01.299292\n| Create Time:\n|  2019-01-23T12:42:37.990070\n|\n--------------------------------------\n| Job 2891970512fa2d5a\n| State: \n|  ok\n| Update Time:\n|  2019-01-23T12:42:37.228769\n| Create Time:\n|  2019-01-23T12:42:32.704471\n|\n--------------------------------------\nProblem in history with id 2891970512fa2d5a - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - fcdata.rdata (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  165.8 KB\n| Dataset Info:\n|  uploaded rdata file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>binary data</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - addFragments (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n|  Fatal error: Exit code 1 ()\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|\n--------------------------------------\n| Job 5729865256bc2525\n| State: \n|  error\n| Update Time:\n|  2019-01-23T12:43:01.299292\n| Create Time:\n|  2019-01-23T12:42:37.990070\n|\n--------------------------------------\n| Job 2891970512fa2d5a\n| State: \n|  ok\n| Update Time:\n|  2019-01-23T12:42:37.228769\n| Create Time:\n|  2019-01-23T12:42:32.704471\n|\n--------------------------------------\n\n--------------------- >> end captured stdout << ----------------------", "test_index": 0, "problem_type": "galaxy.tools.verify.interactor.JobOutputsError"}, "id": "functional.test_toolbox.TestForTool_4c_addfragments.test_tool_000000", "has_data": true}, {"data": {"status": "failure", "tool_id": "4c_choosefragments", "time_seconds": 27.007685899734497, "inputs": {"input2": "chr2L", "input3": "6027", "input1": {"src": "hda", "id": "54f2a3a23292eb07"}, "input4": "6878"}, "tool_version": "1.0.0", "output_problems": ["Job in error state.", "Job in error state."], "job": {"inputs": {"input1": {"src": "hda", "id": "54f2a3a23292eb07", "uuid": "c1fbac0c-e9dd-4295-84bd-4db2abb4bc3e"}}, "update_time": "2019-01-23T12:43:33.536446", "tool_id": "4c_choosefragments", "outputs": {"output1": {"src": "hda", "id": "8155e4b4bf1581ff", "uuid": "96798586-45ea-4e3a-b2cb-9470f7c371df"}}, "stdout": "Failed to activate conda environment! Error was:\n/home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n", "command_line": "Rscript '/tmp/tmpWZS6PQ/job_working_directory/000/4/tmpyPke2Q'", "exit_code": 1, "state": "error", "create_time": "2019-01-23T12:43:09.967273", "params": {"input2": "\"chr2L\"", "input3": "\"6027\"", "chromInfo": "\"/tmp/tmpWZS6PQ/galaxy-dev/tool-data/shared/ucsc/chrom/?.len\"", "dbkey": "\"?\"", "input4": "\"6878\""}, "stderr": "Fatal error: Exit code 1 ()\n", "job_metrics": [], "model_class": "Job", "external_id": "30132", "id": "8155e4b4bf1581ff", "user_email": "test@bx.psu.edu"}, "problem_log": "  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/test/functional/test_toolbox.py\", line 99, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/test/functional/test_toolbox.py\", line 36, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/lib/galaxy/tools/verify/interactor.py\", line 702, in verify_tool\n    raise e\nJob in error state.\nJob in error state.\n-------------------- >> begin captured stdout << ---------------------\nProblem in history with id 5729865256bc2525 - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - addFragments.rdata (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  5.8 MB\n| Dataset Info:\n|  uploaded rdata file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>binary data</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - Choosen Fragments (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n|  Fatal error: Exit code 1 ()\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|\n--------------------------------------\n| Job 8155e4b4bf1581ff\n| State: \n|  error\n| Update Time:\n|  2019-01-23T12:43:33.536446\n| Create Time:\n|  2019-01-23T12:43:09.967273\n|\n--------------------------------------\n| Job 54f2a3a23292eb07\n| State: \n|  ok\n| Update Time:\n|  2019-01-23T12:43:07.466406\n| Create Time:\n|  2019-01-23T12:43:03.106755\n|\n--------------------------------------\nProblem in history with id 5729865256bc2525 - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - addFragments.rdata (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  5.8 MB\n| Dataset Info:\n|  uploaded rdata file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>binary data</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - Choosen Fragments (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n|  Fatal error: Exit code 1 ()\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|\n--------------------------------------\n| Job 8155e4b4bf1581ff\n| State: \n|  error\n| Update Time:\n|  2019-01-23T12:43:33.536446\n| Create Time:\n|  2019-01-23T12:43:09.967273\n|\n--------------------------------------\n| Job 54f2a3a23292eb07\n| State: \n|  ok\n| Update Time:\n|  2019-01-23T12:43:07.466406\n| Create Time:\n|  2019-01-23T12:43:03.106755\n|\n--------------------------------------\n\n--------------------- >> end captured stdout << ----------------------", "test_index": 0, "problem_type": "galaxy.tools.verify.interactor.JobOutputsError"}, "id": "functional.test_toolbox.TestForTool_4c_choosefragments.test_tool_000000", "has_data": true}, {"data": null, "id": "functional.test_toolbox.TestForTool_4c_combinefragends.test_tool_000000", "has_data": false}, {"data": {"status": "failure", "tool_id": "4c_countfragments", "time_seconds": 26.957042932510376, "inputs": {"input2": "4", "input3": "30", "input1": {"src": "hda", "id": "7b55dbb89df8f4e5"}}, "tool_version": "1.0.0", "output_problems": ["Job in error state.", "Job in error state."], "job": {"inputs": {"input1": {"src": "hda", "id": "7b55dbb89df8f4e5", "uuid": "638dcfa0-345b-4bfe-94c7-d8e8c31b134f"}}, "update_time": "2019-01-23T12:44:07.814713", "tool_id": "4c_countfragments", "outputs": {"output1": {"src": "hda", "id": "fa6d20d0fb68383f", "uuid": "6543560c-9bb5-4622-837d-190757d9988e"}}, "stdout": "Failed to activate conda environment! Error was:\n/home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n", "command_line": "Rscript '/tmp/tmpWZS6PQ/job_working_directory/000/6/tmpcuZpX6'", "exit_code": 1, "state": "error", "create_time": "2019-01-23T12:43:44.439673", "params": {"input2": "\"4\"", "input3": "\"30\"", "chromInfo": "\"/tmp/tmpWZS6PQ/galaxy-dev/tool-data/shared/ucsc/chrom/?.len\"", "dbkey": "\"?\""}, "stderr": "Fatal error: Exit code 1 ()\n", "job_metrics": [], "model_class": "Job", "external_id": "30461", "id": "fa6d20d0fb68383f", "user_email": "test@bx.psu.edu"}, "problem_log": "  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/test/functional/test_toolbox.py\", line 99, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/test/functional/test_toolbox.py\", line 36, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpWZS6PQ/galaxy-dev/lib/galaxy/tools/verify/interactor.py\", line 702, in verify_tool\n    raise e\nJob in error state.\nJob in error state.\n-------------------- >> begin captured stdout << ---------------------\nProblem in history with id 8155e4b4bf1581ff - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - chooseFragments.rdata (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  168.0 KB\n| Dataset Info:\n|  uploaded rdata file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>binary data</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - Count Fragments (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n|  Fatal error: Exit code 1 ()\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|\n--------------------------------------\n| Job fa6d20d0fb68383f\n| State: \n|  error\n| Update Time:\n|  2019-01-23T12:44:07.814713\n| Create Time:\n|  2019-01-23T12:43:44.439673\n|\n--------------------------------------\n| Job 7b55dbb89df8f4e5\n| State: \n|  ok\n| Update Time:\n|  2019-01-23T12:43:41.702101\n| Create Time:\n|  2019-01-23T12:43:37.490322\n|\n--------------------------------------\nProblem in history with id 8155e4b4bf1581ff - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - chooseFragments.rdata (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  168.0 KB\n| Dataset Info:\n|  uploaded rdata file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>binary data</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - Count Fragments (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n|  Fatal error: Exit code 1 ()\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  Failed to activate conda environment! Error was:\n|  /home/ubuntu/miniconda3/etc/profile.d/conda.sh: /home/ubuntu/miniconda3/bin/conda: /home/ubuntu/miniconda3/bin/python: bad interpreter: No such file or directory\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|\n--------------------------------------\n| Job fa6d20d0fb68383f\n| State: \n|  error\n| Update Time:\n|  2019-01-23T12:44:07.814713\n| Create Time:\n|  2019-01-23T12:43:44.439673\n|\n--------------------------------------\n| Job 7b55dbb89df8f4e5\n| State: \n|  ok\n| Update Time:\n|  2019-01-23T12:43:41.702101\n| Create Time:\n|  2019-01-23T12:43:37.490322\n|\n--------------------------------------\n\n--------------------- >> end captured stdout << ----------------------", "test_index": 0, "problem_type": "galaxy.tools.verify.interactor.JobOutputsError"}, "id": "functional.test_toolbox.TestForTool_4c_countfragments.test_tool_000000", "has_data": true}, {"data": null, "id": "functional.test_toolbox.TestForTool_4c_getannotation.test_tool_000000", "has_data": false}, {"data": null, "id": "functional.test_toolbox.TestForTool_4c_getdifferences.test_tool_000000", "has_data": false}, {"data": null, "id": "functional.test_toolbox.TestForTool_4c_getzscores.test_tool_000000", "has_data": false}, {"data": null, "id": "functional.test_toolbox.TestForTool_4c_plotreplicates.test_tool_000000", "has_data": false}, {"data": null, "id": "functional.test_toolbox.TestForTool_4c_smoothcounts.test_tool_000000", "has_data": false}], "version": "0.1", "exit_code": 1, "summary": {"num_skips": 0, "num_errors": 0, "num_failures": 9, "num_tests": 9}}